name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Checkout code and LFS files
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true  # Ensure LFS files are downloaded

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Ensure correct Python version

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Verify files exist
    - name: Debug file paths
      run: |
        echo "Working Directory: $(pwd)"
        echo "Listing all files:"
        ls -R
        echo "Checking data directory:"
        if [ -d "data" ]; then
          echo "Data directory exists"
        else
          echo "Data directory missing"
        fi
        echo "Checking data/housing.csv:"
        if [ -f "data/housing.csv" ]; then
          echo "Housing CSV exists"
        else
          echo "Housing CSV missing"
        fi
        echo "Checking model directory:"
        if [ -d "model" ]; then
          echo "Model directory exists"
        else
          echo "Model directory missing"
        fi
        echo "Checking model/housing_price_model.joblib:"
        if [ -f "model/housing_price_model.joblib" ]; then
          echo "Model file exists"
        else
          echo "Model file missing"
        fi

    # Run tests
    - name: Run tests
      run: |
        pytest tests --disable-warnings
