name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true  # Ensure LFS files are downloaded

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Ensure Python version matches your local environment

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Debug paths and check for necessary files
    - name: Debug paths and file existence
      run: |
        echo "Current working directory: $(pwd)"
        echo "Listing all files:"
        ls -R
        echo "Checking if data file exists:"
        test -f data/housing.csv && echo "data/housing.csv exists" || echo "data/housing.csv is missing"
        echo "Checking if model file exists:"
        test -f model/housing_price_model.joblib && echo "model/housing_price_model.joblib exists" || echo "model file is missing"

    # Run tests
    - name: Run tests
      run: pytest tests --disable-warnings
