name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Or use another runner, depending on your setup
    
    steps:
    # Checkout code (with LFS support)
    - name: Checkout repository
      uses: actions/checkout@v3  # Use the latest version of actions/checkout
      with:
        lfs: true  # Ensure Git LFS files are downloaded

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Update this to the correct Python version you're using

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Pull LFS files (make sure they're available)
    - name: Set up Git LFS
      run: git lfs pull  # Pull all LFS files during the CI run

    # Check if LFS files are available
    - name: Check pulled files
      run: |
        # Print the current working directory
        echo "Current working directory: $(pwd)"
        
        # List files recursively to confirm the paths
        ls -R

        # Check if housing.csv is accessible
        echo "Checking data/housing.csv"
        cat data/housing.csv || echo "housing.csv not found"
        
        # Check if model directory contains files
        echo "Checking model directory"
        ls model/ || echo "Model directory not found"

    # Run the tests
    - name: Run tests
      run: |
        # Ensure you're in the correct directory
        cd tests  # Change to the tests directory
        pytest  # Run your tests
