name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Use your project's Python version

      # Step 3: Cache dependencies
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-
      # Step 4: Install dependencies
      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Ensure MLflow is running
      - name: Start MLflow server (if needed)
        run: |
          nohup mlflow server --host 0.0.0.0 --port 5000 &

      # Step 6: Run tests
      - name: Run Tests
        run: pytest tests --disable-warnings

      # Step 7: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 8: Build the Docker image
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/california-housing-app:latest

      # Step 9: Deploy Docker Container
      - name: Deploy Docker Container
        run: |
          docker container stop california-housing-app || true
          docker container rm california-housing-app || true
          docker run -d --name california-housing-app -p 8501:8501 ${{ secrets.DOCKER_USERNAME }}/california-housing-app:latest
